development:
  stripe_secret_key: 'sk_test_51LGFgaSDRTplecUgmRDvrF78HLc5uWrGbQURUiVIKsT1MGDJWfeeqANgBJgvml0x2leclDSVO7czE4Z5lWeiEqgg00pCJf0Pd8'
  stripe_publishable_key: 'pk_test_51LGFgaSDRTplecUgk4lWsw5gzcaPfpmQOynBfh8tTHNuV5MvpHEmJRKD7KP8omnosAdoCMC7OB9K3mXpC8aYOCRF00De7m6Cfa'